"""Database package for Beyonders Urban Intelligence."""

from database.connection import (
    SessionLocal,
    create_db_engine,
    db_session,
    default_engine,
    get_database_url,
    get_db,
    init_db,
)
from database.enums import (
    ConnectivityState,
    Department,
    EventType,
    IncidentStatus,
    Severity,
    TicketStatus,
)
from database.identifiers import (
    generate_bus_id,
    generate_event_id,
    generate_incident_id,
    generate_observation_id,
    generate_ticket_id,
    generate_workorder_id,
    validate_bus_id,
    validate_event_id,
    validate_incident_id,
    validate_observation_id,
    validate_ticket_id,
    validate_workorder_id,
)
from database.models import (
    Base,
    Bus,
    Event,
    Incident,
    IncidentObservation,
    Observation,
    Ticket,
    TicketStatusHistory,
)
from database.operations import (
    create_observation,
    create_or_update_incident,
    create_ticket,
    get_or_create_bus,
    insert_event_idempotent,
    link_observation_to_incident,
    transition_ticket_status,
)
from database.spatial import (
    find_incidents_near,
    find_observations_near,
    haversine_distance_meters,
    query_incidents_in_bbox,
    query_observations_in_bbox,
)

__all__ = [
    "Base",
    "Bus",
    "Event",
    "Observation",
    "Incident",
    "IncidentObservation",
    "Ticket",
    "TicketStatusHistory",
    "EventType",
    "Severity",
    "ConnectivityState",
    "IncidentStatus",
    "TicketStatus",
    "Department",
    "get_db",
    "db_session",
    "create_db_engine",
    "default_engine",
    "SessionLocal",
    "init_db",
    "get_database_url",
    "get_or_create_bus",
    "insert_event_idempotent",
    "create_observation",
    "link_observation_to_incident",
    "create_or_update_incident",
    "create_ticket",
    "transition_ticket_status",
    "find_incidents_near",
    "find_observations_near",
    "query_incidents_in_bbox",
    "query_observations_in_bbox",
    "haversine_distance_meters",
    "validate_bus_id",
    "validate_event_id",
    "validate_observation_id",
    "validate_incident_id",
    "validate_ticket_id",
    "validate_workorder_id",
    "generate_bus_id",
    "generate_event_id",
    "generate_observation_id",
    "generate_incident_id",
    "generate_ticket_id",
    "generate_workorder_id",
]
